services:
  code-academy-backend:
    container_name: code-academy-backend
    build:
      context: .
      target: backend-php
    working_dir: /var/www
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
    networks:
      - shared-net
      
networks:
  shared-net:
    external: true
